apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test
spec:
  tasks:
    - name: inline
      taskSpec:
        params:
        - default: Chuck Norris
          name: name
          type: string
        steps:
        - image: registry.access.redhat.com/ubi7/ubi-minimal:7.8-366
          name: echo
          resources: {}
          script: |
            #!/usr/bin/env bash
            printf "Hello, %s" "$(params.name)"
    - name: testref
      taskRef:
        name: test