apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
  - image: registry.access.redhat.com/ubi7/ubi-minimal:7.8-366
    name: echo
    resources: {}
    script: |
      #!/usr/bin/env bash
      printf "Hello, world"
