apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  steps:
  - image: bash:latest
    name: echo
    resources: {}
    script: |
      #!/usr/bin/env bash
      printf "Hello, world"
