apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  params:
    - default: Raffael
      name: name
      type: string
  results:
    - description: Greeting message
      name: greet
  steps:
    - image: registry.access.redhat.com/ubi7/ubi-minimal:7.8-366
      name: clone
      resources: {}
      script: |
        #!/usr/bin/env bash
        printf "Hello, %s" "$(params.name)" > "$(results.greet.path)"
