apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secret-test
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  steps:
  - image: bash:latest
    name: echo
    resources: {}
    script: |
      #!/usr/bin/env bash
      echo "My secret is $PASSWORD"
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-tekton-secret
            key: password