apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-when
spec:
  params:
    - name: name
      type: string
      default: "Chuck Norris"
  tasks:
    - name: inline
      taskSpec:
        params:
        - default: Chuck Norris
          name: name
          type: string
        steps:
        - image: bash:latest
          name: task-1
          resources: {}
          script: |
            #!/usr/bin/env bash
            printf "Hello, %s" "$(params.name)"
      when:
      - input: "$(params.name)"
        operator: notin
        values: ["Captain Awesome", "Captain Obvious"]
    - name: task-2
      taskRef:
        name: test-when
      when:
      - input: "$(params.name)"
        operator: in
        values: ["Chuck Norris"]