apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-when
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  steps:
  - image: bash:latest
    name: echo
    resources: {}
    script: |
      #!/usr/bin/env bash
      printf "Hello, Chuck"
