apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-build
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  description: >-
    This Task is Golang task to build Go projects.
  params:
  - name: GOOS
    description: "running program's operating system target"
    default: linux
  - name: GOARCH
    description: "running program's architecture target"
    default: amd64
  workspaces:
  - name: source
  steps:
  - name: build
    image: docker.io/library/golang:alpine
    workingDir: $(workspaces.source.path)/go
    script: |
      echo "building go for $(params.GOOS)/$(params.GOARCH)"
      go build main.go -o awesome-go
      ls -lah
    env:
    - name: GOOS
      value: "$(params.GOOS)"
    - name: GOARCH
      value: "$(params.GOARCH)"
