apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trivy-scanner-run
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  pipelineRef:
    name: trivy-scanner-pipeline
  params:
  - name: image
    value: "registry.puzzle.ch/docker.io/alpine"