apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitea-upload
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  description: This Task upload files to your Gitea instance.
  params:
    - description: path to file
      name: file
      type: string
    - default: 'https://gitea.example.com'
      description: Url to gitea instance
      name: giteaUrl
      type: string
    - description: username
      name: username
      type: string
    - description: password
      name: password
      type: string
    - default: 1.0.0
      description: version of the published file
      name: version
      type: string
    - description: upload name of the file
      name: filename
      type: string
  steps:
    - args:
        - '--user'
        - '$(params.username):$(params.password)'
        - '--upload-file'
        - $(params.file)
        - >-
          $(params.giteaUrl)/api/packages/$(params.username)/generic/test/$(params.version)/$(params.filename)
      image: registry.puzzle.ch/docker.io/curl
      name: upload
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
