apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: workflow-pr-
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  pipelineRef:
    name: workflow-pipeline
  workspaces:
    - name: ws-1 # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 2Gi
    - name: maven-settings
      emptyDir: {}