apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    ch.acend/lab: "tekton-basics"
  name: workflow-pipeline
spec:
  params:
    - name: language
      description: Programming language used
      default: java
    - name: repository
      description: Repository to checkout
      default: https://github.com/acend/awesome-apps
    - name: application
      description: Application subpath in repository
      default: java-quarkus
  tasks:
    - name: git-clone
      params:
      - name: url
        value: $(params.repository)
      - name: revision
        value: feature/quarkus-app
      workspaces:
      - name: output
        workspace: ws-1
      taskRef:
        name: git-clone
        kind: ClusterTask
    - name: build
      runAfter:
      - git-clone
      params:
      - name: CONTEXT_DIR
        value: java-quarkus
      - name: GOALS
        value: ["package"]
      - name: MAVEN_IMAGE
        value: maven:3.8.4-openjdk-17
      workspaces:
      - name: source
        workspace: ws-1
      - name: maven-settings
        workspace: maven-settings
      taskRef:
        name: maven
        kind: Task
  workspaces:
  - name: ws-1
  - name: maven-settings