apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-go-run-
spec:
  pipelineRef:
    name: build-go
  podTemplate:
    dnsPolicy: None
    dnsConfig:
      nameservers:
        - 8.8.8.8
  workspaces:
  - emptyDir: {}
    name: ws-1
  params:
  - name: repo-url
    value: ssh://1000820005@ssh.gitea.training.openshift.ch:2222/user5555/awesome-apps.git