apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: private-clone
  labels:
    ch.acend/lab: "tekton-basics"
spec:
  params:
    - name: repository
      description: Repository to checkout
      default: ssh://1000820005@ssh.gitea.apps.training.openshift.ch/user5555/awesome-apps.git
  workspaces:
  - name: ws-1
  tasks:
    - name: git-clone
      workspaces:
      - name: output
        workspace: ws-1
      params:
      - name: url
        value: $(params.repository)
      taskRef:
        name: git-clone
