[params]
enabledModule = "base openshift"
distroName = "OpenShift"
cliToolName = "oc"
appDomain = "apps.training.openshift.ch"
webConsoleURL = "https://console.apps.training.openshift.ch/"
giteaUrl = "gitea.apps.training.openshift.ch"
