[params]
enabledModule = "base openshift"
distroName = "OpenShift"
cliToolName = "oc"
appDomain = "training.openshift.ch"
webConsoleURL = "https://console.training.openshift.ch/"
giteaUrl = "gitea.training.openshift.ch"
