apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-go-pr-
spec:
  params:
  - name: image
    value: ttl.sh/02a77e8d-d633-4686-a401-cc92129e2270:1h
  - name: application
    value: go
  - name: context
    value: /workspace/source/go/.
  - name: dockerfile
    value: ./Dockerfile
  pipelineRef:
    name: build-go-2
  workspaces:
    - name: ws-1 # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi