apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    ch.acend/lab: "tekton-basics"
  name: tekton-trigger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    ch.acend/lab: "tekton-basics"
  name: tekton-triggers-example-minimal
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
  # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["get", "list", "watch", "patch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    ch.acend/lab: "tekton-basics"
  name: tekton-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-example-minimal
subjects:
- kind: ServiceAccount
  name: tekton-trigger