apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  labels:
    ch.acend/lab: "tekton-basics"
  name: java-pipeline-pipelinebinding
spec:
  params:
    - name: repository
      value: $(body.repository)
    - name: application
      value: $(body.application)
    - name: image
      value: $(body.image)
    - name: context
      value: $(body.context)
    - name: dockerfile
      value: $(body.dockerfile)